# Generated by Django 2.2.5 on 2020-07-09 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('P', 'Private')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.ManyToManyField(related_name='emails', to='administration.Email')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('P', 'Private')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('B', 'Bachiller'), ('S', 'University')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.Person')),
                ('bank_account', models.CharField(max_length=50, unique=True)),
            ],
            bases=('administration.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.Person')),
                ('scholar_level', models.CharField(choices=[('B', 'Bachiller'), ('S', 'University')], max_length=20)),
                ('responsables', models.ManyToManyField(related_name='responsables', to='administration.Responsable')),
            ],
            bases=('administration.person',),
        ),
        migrations.CreateModel(
            name='ServiceSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('time_section', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Nigth')], max_length=20)),
                ('cost', models.FloatField()),
                ('salary', models.FloatField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_places', to='administration.ServicePlace')),
                ('typeof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='administration.ServiceType')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ManyToManyField(related_name='phones', to='administration.Phone'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.Person')),
                ('bank_account', models.CharField(max_length=50, unique=True)),
                ('aviable_signature', models.ManyToManyField(related_name='signatures', to='administration.Signature')),
            ],
            bases=('administration.person',),
        ),
        migrations.CreateModel(
            name='StudentResponsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, choices=[('F', 'Father'), ('M', 'Mother'), ('T', 'Tutor')], max_length=10, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Responsable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('hours', models.FloatField()),
                ('facture', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ServiceSignature')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='administration.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='administration.Teacher')),
            ],
        ),
    ]
